title: Cooking Book
description: "Lots of recipes for penguin meat"
author:
  name: "M3LV1N"
  email: "olivet.melvin@gmail.com"
  url: "https://melv1no.github.io"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "M3LV1N"
year : "2023"
